INSERT INTO TBL_PERSON (name, phone) VALUES ('Admin', '11 123456789');
INSERT INTO TBL_PERSON (name, phone) VALUES ('User', '11 987654321');

INSERT INTO TBL_USER (PERSON_ID, email, password) VALUES (1, 'admin@example.com', '123456');
INSERT INTO TBL_USER (PERSON_ID, email, password) VALUES (2, 'user@example.com', '123456');

INSERT INTO TBL_ROLE (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO TBL_ROLE (ROLE) VALUES ('ROLE_OPERATOR');

INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (1, 1);
INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (2, 1);

INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (2, 2);